version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - /data/postgres_db:/opt/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGPORT: 5433
      PGDATA: /opt/data
    logging:
      options:
        max-size: 10m
    networks:
      - net

  db-migrations:
    depends_on:
      - db
    image: binance-bot/db-migrations:1.0
    restart: on-failure
    command:
      - "-url=jdbc:postgresql://db:5433/postgres"
      - "-user=postgres"
      - "-password=postgres"
      - "-community"
      - "-locations=filesystem:/opt/db_migrations"
      - "migrate"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    logging:
      options:
        max-size: 10m
    networks:
      - net

networks:
  net:
    driver: bridge
